version: "3.9"
services:
  bot:
    image: ghcr.io/fmh-charity/it_vzabote_bot:1.0.0
#    image: isaroot/it_vzabote_bot:1.0.0
    stop_signal: SIGINT
    restart: always
    environment:
      TOKEN: "${TOKEN:-0123456789:Zzssxx}"
      pg_db_user: "${pg_db_user:-postgres}"
      pg_db_password: "${pg_db_password:-123}"
      pg_db_host: "${pg_db_host:-pg_database}"
      pg_db_port: ${pg_db_port:-5432}
      pg_db_database: "${pg_db_database:-FMH_BOT_DB}"
      pg_db_schema: "${pg_db_schema:-FMH_BOT_DB}"
