version: "3.9"
services:
  bot:
    image: isaroot/it_vzabote_bot:v1
    stop_signal: SIGINT
    restart: always
    environment:
      - TOKEN
      - pg_db_user
      - pg_db_password
      - pg_db_host
      - pg_db_port
      - pg_db_database
      - pg_db_schema
      - bot_owner_id
