"""
initial create tables
"""

from yoyo import step

__depends__ = {}

# steps = [
step("""CREATE TABLE users (
        user_id int8 NOT NULL, -- telegram id пользователя
        username text NULL, -- Юзернейм (с собакой) при наличии
        firstname text NULL,
        lastname text NULL,
        "access" int4 NULL,
        CONSTRAINT users_pkey PRIMARY KEY (user_id));
    """, "DROP TABLE users")
step("COMMENT ON COLUMN users.user_id IS 'telegram id пользователя';")
step("COMMENT ON COLUMN users.username IS 'Юзернейм (с собакой) при наличии';")
step("""CREATE TABLE group_chat (
        id int4 NOT NULL,
        chat_id int8 NOT NULL, -- Телеграмм-идентификатор чата
        linked_chat_id int8 NULL, -- Привязанный к чату канал (при наличии)
        chat_title text NULL,
        chat_fullname text NULL,
        chat_description text NULL,
        chat_type text NULL,
        CONSTRAINT group_chat_chat_id_key UNIQUE (chat_id),
        CONSTRAINT group_chat_pkey PRIMARY KEY (id)
    );""", "DROP TABLE group_chat")
step("COMMENT ON COLUMN group_chat.chat_id IS 'Телеграмм-идентификатор чата';")
step("COMMENT ON COLUMN group_chat.linked_chat_id IS 'Привязанный к чату канал (при наличии)';")
step("""CREATE TABLE ui_links (
        id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        url_key text NULL,
        url text NULL,
        "label" text NULL,
        CONSTRAINT ui_links_pkey PRIMARY KEY (id)
    );""", "DROP TABLE ui_links;")
step("CREATE UNIQUE INDEX ui_links_url_key_idx ON ui_links USING btree (url_key);", "DROP INDEX ui_links_url_key_idx;")
step("""CREATE TABLE ui_type (
        id int4 NOT NULL GENERATED ALWAYS AS IDENTITY,
        "name" varchar NOT NULL UNIQUE, -- Тип объекта
        description varchar NULL -- Описание объекта (при необходимости)
    );""", "DROP TABLE ui_type;")
step("CREATE UNIQUE INDEX ui_type_id_idx ON ui_type USING btree (id);", "DROP INDEX ui_type_id_idx;")
step("COMMENT ON TABLE ui_type IS 'Таблица с описанием типов объекта';")
step("""COMMENT ON COLUMN ui_type."name" IS 'Тип объекта';""")
step("COMMENT ON COLUMN ui_type.description IS 'Описание объекта (при необходимости)';")
step("""CREATE TABLE ui_form (
        id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "key" varchar NOT NULL, -- поле ключа
        type_id int4 NOT NULL, -- id поля типа';
        "sequence" int4 NOT NULL,
        value varchar NULL, -- Текстовое содержимое
        "access" int4 NULL,
        CONSTRAINT fk_ui_type_id FOREIGN KEY (type_id) REFERENCES ui_type(id) ON DELETE CASCADE ON UPDATE CASCADE
    );""", "DROP TABLE ui_form;")
step("CREATE UNIQUE INDEX ui_form_id_idx ON ui_form USING btree (id);", "DROP INDEX ui_form_id_idx")
step("CREATE UNIQUE INDEX ui_form_key_idx ON ui_form USING btree (key, sequence);", "DROP INDEX ui_form_key_idx")
step("""COMMENT ON COLUMN ui_form."key" IS 'поле ключа';""")
step("COMMENT ON COLUMN ui_form.type_id IS 'id поля типа';")
step("COMMENT ON COLUMN ui_form.value IS 'Текстовое содержимое';")
# ]
